version: 0.2

phases:
  install:
    commands:
      - echo Installing Python and dependencies...
      - powershell Install-PackageProvider -Name NuGet -Force
      - powershell Install-Module -Name PowerShellGet -Force -AllowClobber
      - powershell Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
      - powershell Install-Package -Name python -Source chocolatey -Force
      - python --version
      - pip install --upgrade pip
      - pip install pyinstaller
      - pip install pygame tkinter

  build:
    commands:
      - echo Building the .exe file using PyInstaller...
      - python setup.py

  post_build:
    commands:
      - echo Build completed. Uploading to S3...
      - aws s3 cp dist\flappy_bird.exe s3://builddb/game/

artifacts:
  files:
    - dist\flappy_bird.exe
